Song/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import SongHomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('list/', include('lyric.urls', namespace='lyric')),
    path('', SongHomeView.as_view(), name='home')
]

lyric/urls.py
from django.urls import path,re_path
from .views import (
    LyricListView,
    LyricDetailView,
    LyricGenreListView,
    LyricCreateView,
    LyricManageView,
    LyricDeleteView,
    LyricUpdateView
)

app_name = 'lyric'

urlpatterns = [
    re_path(r'^(?P<page>\d+)$', LyricListView.as_view(), name='list'),
    re_path(r'^detail/(?P<slug>[\w-]+)$', LyricDetailView.as_view(), name='detail'),
    re_path(r'^genre/(?P<genre>[\w]+)/(?P<page>\d+)$', LyricGenreListView.as_view(), name='genre'),
    path('create/', LyricCreateView.as_view(), name='create'),
    path('manage/', LyricManageView.as_view(), name='manage'),
    re_path(r'^manage/delete/(?P<pk>\d+)$', LyricDeleteView.as_view(), name='delete'),
    re_path(r'^manage/update/(?P<pk>\d+)$', LyricUpdateView.as_view(), name='update'),
]

lyric/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils import timezone

class Lyric(models.Model):
    title = models.CharField(max_length=255)
    lyrics = models.TextField()
    genre = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(null=True)
    published = models.DateTimeField(null=True)
    slug = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.title)
        if self.is_published == True:
            self.published = timezone.now()
        else:
            self.published = None
        super().save()

    def get_absolute_url(self):
        url_slug = {'slug': self.slug}
        return reverse('lyric:detail', kwargs=url_slug)
    

    def __str__(self):
        return '{}. {} - {}'.format(self.id, self.title, self.artist)

lyric/forms.py
from django.forms import ModelForm
from .models import Lyric

class LyricForm(ModelForm):
    class Meta:
        model = Lyric
        fields=[
            'title',
            'lyrics',
            'genre',
            'artist',
        ]

Song/views.py
from typing import Any
from django.views.generic import TemplateView
from lyric.views import SongGenre


class SongHomeView(TemplateView, SongGenre):
    template_name = 'index.html'

    def get_context_data(self, **kwargs: Any):
        queryset = self.get_latest_song()
        context={
            'latest_song_list': queryset
        }    
        return context

lyric/views.py
from typing import Any
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView
)
from .models import Lyric
from .forms import LyricForm

class SongGenre():
    model = Lyric
    
    def get_latest_song(self):
        listGenre = self.model.objects.values_list('genre', flat=True).distinct()
        queryset = []

        for genre in listGenre:
            lyric = self.model.objects.filter(genre=genre).latest('published')
            queryset.append(lyric)
        
        return queryset

class LyricGenreListView(ListView):
    model = Lyric
    template_name = 'lyric/lyric_genre_list.html'
    ordering = ['-published']
    context_object_name = 'lyric_list'
    paginate_by = 2

    def get_queryset(self):
        self.queryset = self.model.objects.filter(genre = self.kwargs['genre'])
        return super().get_queryset()
    
    def get_context_data(self, *args, **kwargs):
        listGenre = self.model.objects.values_list('genre', flat=True).distinct().exclude(genre=self.kwargs['genre'])
        self.kwargs.update({
            'listGenre': listGenre
        })
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

class LyricListView(ListView):
    model = Lyric
    template_name = 'lyric/lyric_list.html'
    context_object_name = 'lyric_list'
    ordering = ['-published']
    paginate_by = 3

    def get_context_data(self, *args, **kwargs):
        listGenre = self.model.objects.values_list('genre', flat=True).distinct()
        self.kwargs.update({
            'listGenre': listGenre
        })
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

class LyricDetailView(DetailView):
    model = Lyric
    template_name = 'lyric/lyric_detail.html'
    context_object_name = 'lyric'

    def get_context_data(self, *args, **kwargs):
        listGenre = self.model.objects.values_list('genre', flat=True).distinct()
        relatedSong = self.model.objects.filter(genre=self.object.genre).exclude(id=self.object.id)
        self.kwargs.update({
            'listGenre': listGenre,
            'relatedSong': relatedSong,
        })
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)
    
class LyricCreateView(CreateView):
    form_class = LyricForm
    template_name = 'lyric/lyric_create.html'

class LyricManageView(ListView):
    model = Lyric
    template_name = 'lyric/lyric_manage.html'
    context_object_name = 'lyric_list'

class LyricDeleteView(DeleteView):
    model = Lyric
    template_name = 'lyric/lyric_delete_confirmation.html'
    success_url = reverse_lazy('lyric:manage')

class LyricUpdateView(UpdateView):
    model = Lyric
    form_class = LyricForm
    template_name = 'lyric/lyric_update.html'

lyric/templates/lyric/lyric_create.html
{% extends "base.html" %}

{% block titlePage %}
    Create
{% endblock titlePage %}

{% block contents %}
    <h1>Add New Song</h1>
    <form method='POST'>
        {% csrf_token %}
        <div class="form-group">
            <label for="{{form.title.id_for_label}}">{{form.title.label}}</label>
            <input type="text" class="form-control" name='{{form.title.name}}' maxlength='{{form.title.max}}' required id='{{form.title.id_for_label}}'>
        </div>
        <div class="form-group">
            <label for="{{form.lyrics.id_for_label}}">{{form.lyrics.label}}</label>
            <textarea name="{{form.lyrics.name}}" id="{{form.lyrics.id_for_label}}" class='form-control' rows='10'required></textarea>
        </div>
        <div class="form-group">
            <label for="{{form.genre.id_for_label}}">{{form.genre.label}}</label>
            <input type="text" class="form-control" name='{{form.genre.name}}' maxlength='{{form.genre.max}}' required id='{{form.genre.id_for_label}}'>
        </div>
        <div class="form-group">
            <label for="{{form.artist.id_for_label}}">{{form.artist.label}}</label>
            <input type="text" class="form-control" name='{{form.artist.name}}' maxlength='{{form.artist.max}}' required id='{{form.artist.id_for_label}}'>
        </div>
        <button class='btn btn-primary mt-2'type='Submit'>Submit New Song</button>
    </form>
{% endblock contents %}

lyric/templates/lyric/lyric_delete_confirmation.html
{% extends "base.html" %}

{% block titlePage %}
    Delete
{% endblock titlePage %}

{% block contents %}
    <h1>Delete Confirmation</h1>
    <p>Are You Sure Delete This?</p>
    <h3>{{lyric.title}} - {{lyric.artist}}</h3>
    <form method='POST'>
        {% csrf_token %}
        <button type='submit' class='btn btn-outline-danger'>Yes</button>
        <a class='btn btn-outline-primary' href="{% url "lyric:manage" %}">No</a>
    </form>
{% endblock contents %}

lyric/templates/lyric/lyric_detail.html
{% extends "base.html" %}

{% block titlePage %}
    {{lyric.title}}
{% endblock titlePage %}

{% block contents %}
    <div class="row">
        {% comment %} Genres in Details {% endcomment %}
        <div class="col-md-8">
            <h3>{{lyric.title}}</h3>
            <p>Genre: {{lyric.genre}} | {{lyric.published}}</p>
            <p>Artist: {{lyric.artist}}</p>
            <p>{{lyric.lyrics|linebreaks}}</p>
        </div>
        <div class="col-sm">
            <h3>Genre</h3>
            <ul class="list-group list-group-flush">
                {% for genre in listGenre %}
                <li class="list-group-item">
                    <a href="{% url "lyric:genre" genre 1 %}">
                        {{genre}}
                    </a>
                </li>
                {% endfor %}
            </ul>

            {% comment %} Related Songs {% endcomment %}
            <h3>Related Song</h3>
            <ul class="list-group list-group-flush">
                {% for relate in relatedSong %}
                    {% if forloop.counter is not 3 %}
                        <li class="list-group-item">
                            <h4>
                                <a href="{% url "lyric:detail" relate.slug%}">
                                    {{relate.title}}
                                </a>
                            </h4>
                            <p>{{relate.published|date}}</p>
                            <p>{{relate.lyrics|truncatewords:50}}</p>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="list-group-item">
                    <a href="{% url "lyric:genre" lyric.genre 1 %}">More Song</a>
                </li>
            </ul>
        </div>
    </div>
    
{% endblock contents %}

lyric/templates/lyric/lyric_genre_list.html
{% extends "base.html" %}


{% block titlePage %}
    Song List
{% endblock titlePage %}

{% block contents %}
<h2>Genres: {{genre}}</h2>
    <div class="row">
            <div class='col-md-8'>
                {% for list in lyric_list %}
            <a class = 'text-dark'href="{% url "lyric:detail" list.slug %}">
                <h3>{{list.title}}</h3>
            </a>
            <p>Genre: {{list.genre}} | {{list.published}}</p>
            <p>Artist: {{list.artist}}</p>
            <p class='border-bottom'>{{list.lyrics|truncatewords:50}}
                <a href="% url "lyric:detail" list.slug %}">more</a>
            </p>
            {% endfor %}
            {% if is_paginated %}
            
            {% endif %}
            <nav aria-label="pagination lyric page">
                <ul class="pagination">
                <li class="page-item">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="{% url "lyric:genre" genre page_obj.previous_page_number %}" aria-label="Next">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <a class="page-link" href="#" aria-label="Next" aria-disable='true'>
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>

                {% for i in paginator.page_range %}
                    {% if page is page_obj.number %}
                        <li class="page-item">
                            <a class="page-link" href="#">{{i}}
                                <span class='sr-only'>(current)</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{% url "lyric:genre" genre i %}">{{i}}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                
                {% if page_obj.has_next %}
                    <a class="page-link" href="{% url "lyric:genre" genre page_obj.next_page_number %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% else %}
                    <a class="page-link" href="#" aria-label="Next" aria-disable='true'>
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                {% endif %}
                </ul>
            </nav>
        </div>
        <div class='col-sm'>
            <h3>Genre</h3>
            <ul class="list-group list-group-flush">
                <li class='list-group-item'>
                    <a href="{% url "lyric:list" 1 %}">All Genres</a>
                </li>
                {% for genre in listGenre %}
                    <li class="list-group-item">
                        <a href="{% url "lyric:genre" genre 1%}">
                            {{genre}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
{% endblock contents %}

lyric/templates/lyric/lyric_list.html
{% extends "base.html" %}


{% block titlePage %}
    Song List
{% endblock titlePage %}

{% block contents %}
    <h1>Song List</h1>

    <div class="row">
            <div class='col-md-8'>
                {% for list in lyric_list %}
            <a class = 'text-dark'href="{% url "lyric:detail" list.slug %}">
                <h3>{{list.title}}</h3>
            </a>
            <p>Genre: {{list.genre}} | {{list.published}}</p>
            <p>Artist: {{list.artist}}</p>
            <p class='border-bottom'>{{list.lyrics|truncatewords:50}}
                <a href="{% url "lyric:detail" list.slug %}">more</a>
            </p>
            {% endfor %}
            {% if is_paginated %}
            
            {% endif %}
            <nav aria-label="pagination lyric page">
                <ul class="pagination">
                <li class="page-item">
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="{% url "lyric:list" page_obj.previous_page_number %}" aria-label="Next">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <a class="page-link" href="#" aria-label="Next" aria-disable='true'>
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% endif %}
                </li>

                {% for i in paginator.page_range %}
                    {% if page is page_obj.number %}
                        <li class="page-item">
                            <a class="page-link" href="#">{{i}}
                                <span class='sr-only'>(current)</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{% url "lyric:list" i %}">{{i}}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item">
                    {% if page_obj.has_next %}
                        <a class="page-link" href="{% url "lyric:list" page_obj.next_page_number %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <a class="page-link" href="#" aria-label="Next" aria-disable='true'>
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </li>
                </ul>
            </nav>
        </div>
        <div class='col-sm'>
            <h3>Genre</h3>
            <ul class="list-group list-group-flush">
                {% for genre in listGenre %}
                    <li class="list-group-item">
                        <a href="{% url "lyric:genre" genre 1%}">
                            {{genre}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    
{% endblock contents %}

lyric/templates/lyric/lyric_manage.html
{% extends "base.html" %}

{% block titlePage %}
    Manage Song
{% endblock titlePage %}

{% block contents %}
    <h1>Manage Song</h1>
    <a class='btn btn-primary btn-block mb-3' href='{% url "lyric:create" %}'>Add New Song</a>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title Song</th>
            <th scope="col">Genre</th>
            <th scope="col">Artist</th>
            <th scope="col">Published</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for song in lyric_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{song.title}}</td>
                    <td>{{song.genre}}</td>
                    <td>{{song.artist}}</td>
                    <td>{{song.published}}</td>
                    <td>
                        <a class='btn btn-warning' href='{% url "lyric:update" song.id %}'>Edit</a>
                        <a class='btn btn-danger' href='{% url "lyric:delete" song.id %}'>Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contents %}

lyric/templates/lyric/lyric_update.html
{% extends "base.html" %}

{% block titlePage %}
    UPDATE
{% endblock titlePage %}

{% block contents %}
    <h1>Add New Song</h1>
    <form method='POST'>
        {% csrf_token %}
        <div class="form-group">
            <label for="{{form.title.id_for_label}}">{{form.title.label}}</label>
            <input type="text" class="form-control" name='{{form.title.name}}' maxlength='{{form.title.max}}' required id='{{form.title.id_for_label}}' value='{{form.title.value}}'>
        </div>
        <div class="form-group">
            <label for="{{form.lyrics.id_for_label}}">{{form.lyrics.label}}</label>
            <textarea name="{{form.lyrics.name}}" id="{{form.lyrics.id_for_label}}" class='form-control' rows='10'required>{{form.lyrics.value}}</textarea>
        </div>
        <div class="form-group">
            <label for="{{form.genre.id_for_label}}">{{form.genre.label}}</label>
            <input type="text" class="form-control" name='{{form.genre.name}}' maxlength='{{form.genre.max}}' required id='{{form.genre.id_for_label}}' value='{{form.genre.value}}'>
        </div>
        <div class="form-group">
            <label for="{{form.artist.id_for_label}}">{{form.artist.label}}</label>
            <input type="text" class="form-control" name='{{form.artist.name}}' maxlength='{{form.artist.max}}' required id='{{form.artist.id_for_label}}' value='{{forn.artist.value}}'>
        </div>
        <button class='btn btn-warning mt-2'type='Submit'>Update Song</button>
        <a href="{% url "lyric:manage" %}" class='btn btn-danger mt-2'>No</a>
    </form>
{% endblock contents %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    <title>
        {% block titlePage %}{% endblock titlePage %}
    </title>
</head>
<body>
    {% include "snippets/navbar.html" %}
    <div class="container">
        {% block contents %}{% endblock contents %}
    </div>
    {% include "snippets/scripts.html" %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block titlePage %}
    Home
{% endblock titlePage %}

{% block contents %}
<h1>Home</h1>
    <div class="row">
        {% for song in latest_song_list %}
        <div class="col-sm-4">
            <div class="card mb-4">
                <div class="card-body">
                <h5 class="card-title">
                    <a class='text-dark'href="{% url "lyric:genre" song.genre 1%}">
                        {{song.genre}}
                    </a>
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">{{song.title}}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{song.published|date}}</h6>
                <p class="card-text">{{song.lyrics|truncatewords:10}}</p>
                <a href="{% url "lyric:detail" song.slug %}" class="card-link">More Detail</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    

    
{% endblock contents %}

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">KazeLyric</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "lyric:list" 1 %}">Song List</a>
                </li>
            </ul>
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{user}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "lyric:create" %}">Add New Song</a>
                    <a class="dropdown-item" href="{% url "lyric:manage" %}">Manage Song</a>
                </div>
            </div>
        </div>
    </div>
</nav>

templates/snippets/scripts.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">